name: pytest

on:
  push:
    branches:
      - 'main'

  pull_request:

jobs:
  test:
    name: Test Code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install code/
    - name: Test with unittest
      run: |
        cd code
        python -m unittest